# SPDX-FileCopyrightText: 2025 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.systemd.enable = true; # Required for TPM2 unlock
  boot.extraModulePackages = with config.boot.kernelPackages; [ ryzen-smu ];
  boot.kernelParams = [
    "pcie_aspm.policy=powersave"
    "microcode.amd_sha_check=off"
  ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "defaults"
      "size=4g"
      "mode=755"
    ];
  };

  boot.initrd.luks.devices.root = {
    device = "/dev/disk/by-uuid/fd6a423c-fb03-4963-a8bb-45309c99c34e";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  environment.etc.crypttab = {
    mode = "0600";
    text = with config.sops; ''
      # <name> <device>                                  <password>                       <options>
      cache    UUID=764e86a8-67c0-4ffd-bd71-1327a80c2c0c ${secrets."crypttab/cache".path} nofail,x-systemd.device-timeout=5s,discard,no-read-workqueue,no-write-workqueue
      data1    UUID=1288769a-3175-4068-b184-67dc6004b658 ${secrets."crypttab/data1".path} nofail,x-systemd.device-timeout=5s
      data2    UUID=9f0339bc-ef75-4fb7-8125-24a90d5aab92 ${secrets."crypttab/data2".path} nofail,x-systemd.device-timeout=5s
    '';
  };
  sops.secrets."crypttab/cache" = { };
  sops.secrets."crypttab/data1" = { };
  sops.secrets."crypttab/data2" = { };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/76177813-16ba-4a28-98fc-10efcdea03b1";
    fsType = "btrfs";
    options = [
      "subvol=@persist"
      "noatime"
      "compress-force=zstd:1"
    ];
    neededForBoot = true;
  };

  fileSystems."/persist/.snapshots" = {
    device = "/dev/disk/by-uuid/76177813-16ba-4a28-98fc-10efcdea03b1";
    fsType = "btrfs";
    options = [
      "subvol=@snapshots-persist"
      "noatime"
      "compress-force=zstd:1"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/76177813-16ba-4a28-98fc-10efcdea03b1";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "noatime"
      "compress-force=zstd:1"
    ];
  };

  fileSystems."/nix/.snapshots" = {
    device = "/dev/disk/by-uuid/76177813-16ba-4a28-98fc-10efcdea03b1";
    fsType = "btrfs";
    options = [
      "subvol=@snapshots-nix"
      "noatime"
      "compress-force=zstd:1"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/76177813-16ba-4a28-98fc-10efcdea03b1";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "noatime"
      "compress-force=zstd:1"
    ];
  };

  fileSystems."/home/.snapshots" = {
    device = "/dev/disk/by-uuid/76177813-16ba-4a28-98fc-10efcdea03b1";
    fsType = "btrfs";
    options = [
      "subvol=@snapshots-home"
      "noatime"
      "compress-force=zstd:1"
    ];
  };

  fileSystems."/etc/nixos" = {
    device = "/home/rharish/nix-configs";
    options = [
      "bind"
      "x-gvfs-hide"
    ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/76177813-16ba-4a28-98fc-10efcdea03b1";
    fsType = "btrfs";
    options = [
      "subvol=@swap"
      "noatime"
      "compress-force=zstd:1"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/777A-2FEB";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/cc21decd-809a-4634-9b81-65a057f945dc";
    fsType = "btrfs";
    options = [
      "nofail"
      "x-systemd.device-timeout=10s"
      "subvol=@"
      "noatime"
      "compress-force=zstd:1"
    ];
  };

  fileSystems."/data/.snapshots" = {
    device = "/dev/disk/by-uuid/cc21decd-809a-4634-9b81-65a057f945dc";
    fsType = "btrfs";
    options = [
      "nofail"
      "x-systemd.device-timeout=10s"
      "subvol=@snapshots"
      "noatime"
      "compress-force=zstd:1"
    ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 8 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  # Set the default interface for NAT.
  networking.nat.externalInterface = "enp6s0";

  # Enable Wake-on-LAN
  networking.interfaces.enp6s0.wakeOnLan.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # To monitor ECC errors
  hardware.rasdaemon.enable = true;

  # NUT for UPS
  power.ups = {
    enable = true;
    ups."shanalotte" = {
      description = "Eaton Ellipse Pro 1120";
      driver = "usbhid-ups";
      port = "auto";
    };
    users."nut-admin" = {
      passwordFile = config.sops.secrets."nut".path;
      upsmon = "primary";
    };
    upsmon.monitor.main = {
      system = "shanalotte";
      user = "nut-admin";
    };
  };
  sops.secrets."nut" = { };
}
