# SPDX-FileCopyrightText: 2025 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

access_control:
  rules:
    - domain: '*.rharish.dev'
      policy: two_factor
session:
  cookies:
    - domain: rharish.dev
      authelia_url: https://auth.rharish.dev
